--USER DEFINED EXCEPTION
SET SERVEROUTPUT ON
DECLARE
BANK_BALANCE NUMBER := 10000;
AMT NUMBER := &AMT;
LESS_AMOUNT EXCEPTION;
RSULT NUMBER;

BEGIN
 IF AMT > BANK_BALANCE THEN
RAISE LESS_AMOUNT ;
ELSE 
RSULT := BANK_BALANCE - AMT;
DBMS_OUTPUT.PUT_LINE(RSULT);
END IF ;

EXCEPTION 
WHEN LESS_AMOUNT THEN
DBMS_OUTPUT.PUT_LINE('INSUFFICIENT FUND');
END;
--===============================================================================
SET SERVEROUTPUT ON
DECLARE
 BANK_BALANCE NUMBER:=10000;
 AMT NUMBER:=&AMT;
 LESS_AMOUNT EXCEPTION;
 RSLT NUMBER;
 
BEGIN
IF AMT>BANK_BALANCE THEN
 RAISE LESS_AMOUNT;
 ELSE
 RSLT:=BANK_BALANCE-AMT;
 DBMS_OUTPUT.PUT_LINE(RSLT);
 END IF;
 EXCEPTION
 WHEN LESS_AMOUNT THEN
 DBMS_OUTPUT.PUT_LINE('INSUFFICIENT FUNDS');
END;









